runtime:
  cache_dir: ./.cache/antora

site:
  title: LAB - 5G RAN Deployments on OpenShift
  url: https://labs.sysdeseng.com/
  start_page: 5g-ran-deployments-on-ocp-lab::index.adoc

content:
  sources:
    - url: ./
      branches:
      - 'lab-4.13'
      start_path: documentation

asciidoc:
  attributes:
    release-version: 4.13
    page-pagination: true
    gh-user: 'RHsyseng'
    gh-branch: 'lab-4.13'
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
#    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.1.9/ui-bundle.zip
    url: ./ui-bundle-telco.zip
    # UI Repo: https://github.com/RHsyseng/rht-tutorial-ui/tree/latest-antora
    # In order to build: gulp bundle
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
