---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: sno-seed
  namespace: sno-seed
spec:
  baseDomain: 5g-deployment.lab
  clusterName: sno-seed
  controlPlaneConfig:
    servingCertificates: {}
#  installed: false
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: sno-seed
    version: v1beta1
  platform:
    agentBareMetal: 
      agentSelector:
        matchLabels:
          cluster-name: "sno-seed"
  pullSecretRef:
    name: pullsecret
