---
controller_credentials:
  - name: "HUB Cluster Kubeconfig"
    description: ""
    credential_type: "Kubeconfig"
    organization: "Lab"
    inputs:
      kube_config: "{{ hub_kubeconfig_file_content }}"

...
