= OpenShift GitOps
include::_attributes.adoc[]
:profile: 5g-ran-lab

GitOps is a big part of how we deploy and manage RAN infrastructure at scale, in this section we are going to cover the basics around GitOps patterns and how we can leverage these in OpenShift.

GitOps can be defined as a set of practices that use Git pull requests to manage infrastructure and application configurations. In GitOps, the Git repository is the only source of truth for system and application configuration. This Git repository contains a declarative description of the infrastructure you need in your specified environment and contains an automated process to make your environment match the described state. Also, it contains the entire state of the system so that the trail of changes to the system state are visible and auditable. By using GitOps, you resolve the issues of infrastructure and application configuration sprawl.

GitOps defines infrastructure and application definitions as code. Then, it uses this code to manage multiple workspaces and clusters to simplify the creation of infrastructure and application configurations. By following the principles of the code, you can store the configuration of clusters and applications in Git repositories, and then follow the Git workflow to apply these repositories to your chosen clusters. You can apply the core principles of developing and maintaining software in a Git repository to the creation and management of your cluster and application configuration files.

[#gitops-principles]
== Principles of GitOps

1. **Declaratively**

    The system's desired state must be declarative.

2. **Immutability**

    Declarations must be stored as immutable versions in Git.

3. **Continuous Reconciliation**

    State reconciliation must be continuous.

4. **Declarative Operations**

    Operations should be through versioned mutation of the declaration.

[#gitops-ocp]
== GitOps on OpenShift

Red Hat OpenShift uses Argo CD to maintain cluster resources. Argo CD is an open-source declarative tool for the continuous integration and continuous deployment (CI/CD) of applications.

Some key features:

* Ensure that the clusters have similar states for configuration, monitoring, and storage.
* Apply or revert configuration changes to multiple OpenShift Container Platform clusters.
* Associate templated configuration with different environments.
* Promote applications across clusters, from staging to production.

You can learn more about OpenShift GitOps https://docs.openshift.com/container-platform/4.11/cicd/gitops/understanding-openshift-gitops.html[here].
