= Configuring Ansible Automation Platform
include::_attributes.adoc[]
:profile: 5g-ran-lab

[#configuring-automation-controller]
== Configuring Automation Controller

[#controller-config-setup]
=== Setup

First, we need to ensure the Automation Hub and Automatin Controller domains are in our `/etc/hosts` file.

[source,bash]
-----
> cat /etc/hosts
...
<hypervisor_ip> automation-hub-aap.apps.hub.5g-deployment.lab automation-aap.apps.hub.5g-deployme    nt.lab
-----

Next, let's gather our Automation Hub and Automation Controller credentials.

[.console-input]
[source,bash]
-----
export GALAXY_NG_USER="admin"
export GALAXY_NG_PASSWORD=$(oc -n aap get secret automation-hub-admin-password -o jsonpath='{.data.password}' | base64 -d)
export ANSIBLE_CTRL_USER="admin"
export ANSIBLE_CTRL_PASSWORD=$(oc -n aap get secret automation-admin-password -o jsonpath='{.data.password}' | base64 -d)
export GALAXY_NG_URL="https://$(oc -n aap get route automation-hub -o jsonpath='{.spec.host}')"
export ANSIBLE_CTRL_URL="https://$(oc -n aap get route automation -o jsonpath='{.spec.host}')"
-----

It is important to register the Red Hat AAP Controller product using a valid subscription. Otherwise, it will prompt the below error when triggering Ansible jobs using ACM hooks.

[source,bash]
-----
fatal: [localhost]: FAILED! => {"changed": false, "msg": "You don't have permission to POST to /api/v2/job_templates/10/launch/ (HTTP 403)."}
-----

We can accomplish this by accessing the link:https://automation-aap.apps.hub.5g-deployment.lab[Automation Controller's web UI] via web browser. From there, login with Red Hat account credentials and select the subscription you wish to use, then you will be redirected to the Automation Hub console.

<image>

We will need to install the link:https://github.com/ansible/awx[AWX] CLI for simple interaction with the Automation controller via command line.

[.console-input]
[source,bash]
-----
pip3 install awxkit
awx --help
-----

We will create authentication tokens for accessing our Automation Hub and Automation Controller, via the Automations Hub API and `awx` CLI for the Automation Controller.

[.console-input]
[source,bash]
-----
curl -sku ${GALAXY_NG_USER}:"${GALAXY_NG_PASSWORD}" -X POST ${GALAXY_NG_URL}/api/galaxy/v3/auth/token/ | jq -r .token > ~/5g-deployment-lab/galaxy_token
awx --conf.host ${ANSIBLE_CTRL_URL} --conf.username ${ANSIBLE_CTRL_USER} --conf.password "${ANSIBLE_CTRL_PASSWORD}" --conf.insecure login | jq -r .token > ~/5g-deployment-lab/tower_token
-----

Lastly, we will login into our OpenShift Hub cluster.

NOTE: replace `<admin_password>` with the OpenShift admin password orivded in the e-mail you received when the lab was ready.

[.console-input]
[source,bash]
-----
oc --kubeconfig ~/5g-deployment-lab/hub-kubeconfig login -u admin -p <admin_password> https://api.hub.5g-deployment.lab:6443 --insecure-skip-tls-verify=true
-----

We now have the necessary components to begin configuring Ansible automation.

[#creating-controller-automation-templates]
=== Creating Controller Automation Templates

First, lets create authorization credentials for accessing our OpenShift Hub. We will start off by creating a credential type with custom inputs and injectors, then create a credential of that credential type.

[.console-input]
[source,bash,subs="+macros,attributes+"]
-----
curl https://raw.githubusercontent.com/{gh-user}/5g-ran-deployments-on-ocp-lab/{gh-branch}/aap-integration-tools/tower-config/credential_inputs_kubeconfig.json -o ~/5g-deployment-lab/credential_inputs_kubeconfig.json
curl https://raw.githubusercontent.com/{gh-user}/5g-ran-deployments-on-ocp-lab/{gh-branch}/aap-integration-tools/tower-config/credential_injector_kubeconfig.json -o ~/5g-deployment-lab/credential_injector_kubeconfig.json
awx --conf.host pass:[${ANSIBLE_CTRL_URL}] --conf.username pass:[${ANSIBLE_CTRL_USER}] --conf.password pass:["${ANSIBLE_CTRL_PASSWORD}"] --conf.insecure credential_types create --name 'kubeconfig' --kind cloud --inputs '@~/5g-deployment-lab/credential_inputs_kubeconfig.json' --injectors '@~/5g-deployment-lab/credential_injector_kubeconfig.json'
awx --conf.host pass:[${ANSIBLE_CTRL_URL}] --conf.username pass:[${ANSIBLE_CTRL_USER}] --conf.password pass:["${ANSIBLE_CTRL_PASSWORD}"] --conf.insecure credentials create --name 'hub-acm-kubeconfig' --organization 'Default' --credential_type 'kubeconfig' --inputs "{'kube_config':'@~/5g-deployment-lab/hub-kubeconfig'}"
-----

Next, we'll create authorization credentials do give our AAP Controller access to the AAP Hub. Since we are using self-signed certificates for the AAP Hub, we will also need to disable SSL certificate verifications.

[.console-input]
[source,bash]
-----
awx --conf.host ${ANSIBLE_CTRL_URL} --conf.username ${ANSIBLE_CTRL_USER} --conf.password "${ANSIBLE_CTRL_PASSWORD}" --conf.insecure credentials create --name 'hub-galaxy-token' --organization 'Default' --credential_type 'Ansible Galaxy/Automation Hub API Token' --inputs "{'url':'$GALAXY_NG_URL/api/galaxy/content/published/','token':'$(cat ~/5g-deployment-lab/galaxy_token)'}"
awx --conf.host ${ANSIBLE_CTRL_URL} --conf.username ${ANSIBLE_CTRL_USER} --conf.password "${ANSIBLE_CTRL_PASSWORD}" --conf.insecure settings modify GALAXY_IGNORE_CERTS true
-----

Since we wish to pull collections from our private Automation Hub, we will configure the Automation Controller default organization to use our custom Automation Hub credentials created above instead of `galaxy.ansible.com` credentials.

[.console-input]
[source,bash]
-----
awx --conf.host "${ANSIBLE_CTRL_URL}" --conf.username "${ANSIBLE_CTRL_USER}" --conf.password "${ANSIBLE_CTRL_PASSWORD}" --conf.insecure organizations disassociate --organization 'Default' --galaxy_credential 'Ansible Galaxy'
awx --conf.host "${ANSIBLE_CTRL_URL}" --conf.username "${ANSIBLE_CTRL_USER}" --conf.password "${ANSIBLE_CTRL_PASSWORD}" --conf.insecure organizations associate --organization 'Default' --galaxy_credential 'hub-galaxy-token'
-----

In the local hosted git repository at https://infra.5g-deployment.lab:3000/student/5g-ran-deployments-on-ocp-lab/, notice a directory named aap-integration-tools. This directory contains relevant configuration files that we will be using for AAP automation. We will be using the Ansible Controller's source control management feature to manage our automation file and automatically update our automation project when the source is updated.

We will create an Ansible project using this git repository as our target.

[.console-input]
[source,bash,subs="+macros,attributes+"]
-----
awx --conf.host pass:[${ANSIBLE_CTRL_URL}] --conf.username pass:[${ANSIBLE_CTRL_USER}] --conf.password pass:["${ANSIBLE_CTRL_PASSWORD}"] --conf.insecure projects create --name 'aap-for-ran-ztp-project' --organization 'Default' --wait --scm_type git --scm_url https://infra.5g-deployment.lab:3000/student/5g-ran-deployments-on-ocp-lab.git --scm_branch {gh-branch}
-----

Since each Ansible deployment needs a list of hosts it can run on, we will create an inventory along with a dynamic inventory source.

[.console-input]
[source,bash]
-----
awx --conf.host ${ANSIBLE_CTRL_URL} --conf.username ${ANSIBLE_CTRL_USER} --conf.password "${ANSIBLE_CTRL_PASSWORD}" --conf.insecure inventory create --name 'hub-acm-inventory' --organization 'Default'
awx --conf.host ${ANSIBLE_CTRL_URL} --conf.username ${ANSIBLE_CTRL_USER} --conf.password "${ANSIBLE_CTRL_PASSWORD}" --conf.insecure inventory_sources create --name 'acm-dynamic-inventory' --organization 'Default' --inventory 'hub-acm-inventory' --update_on_launch true --credential 'hub-acm-kubeconfig' --source scm --source_project 'aap-for-ran-ztp-project' --source_path 'aap-integration-tools/inventories/cluster-inventory-example.yml'
-----

Now, we create our job template and associate the template with our ACM Hub credentials. This is the job template for the Ansible job that gets invoked by ACM. The jobe template we create is associated with our created project and inventory, a playbook to run in our git repository, and any extra variables we wish to add as input.

[.console-input]
[source,bash]
-----
awx --conf.host ${ANSIBLE_CTRL_URL} --conf.username ${ANSIBLE_CTRL_USER} --conf.password "${ANSIBLE_CTRL_PASSiWORD}" --conf.insecure job_templates create --name 'ztp-day2-automation-template' --project 'aap-for-ran-ztp-project' --playbook 'aap-integration-tools/playbooks/cluster-mgmt.yml' --inventory 'hub-acm-inventory' --ask_variables_on_launch true --allow_simultaneous true --extra_vars '{"state": "present", "namespace_to_add": "ztp-day2-automation"}'
awx --conf.host ${ANSIBLE_CTRL_URL} --conf.username ${ANSIBLE_CTRL_USER} --conf.password "${ANSIBLE_CTRL_PASSWORD}" --conf.insecure job_templates associate 'ztp-day2-automation-template' --credential 'hub-acm-kubeconfig'
-----

[#installing-mch-addons]
== Installing MultiClusterHub Add-Ons

Let's patch MultiClusterHub with the necessary add-ons to enable our OpenShift Hub to access and configure spoke clusters.

[.console-input]
[source,bash]
-----
oc patch mch multiclusterhub -n open-cluster-management --type=json -p='[{"op": "add", "path": "/spec/overrides/components/-","value":{"name":"cluster-proxy-addon","enabled":true}}]'
oc patch mch multiclusterhub -n open-cluster-management --type=json -p='[{"op": "add", "path": "/spec/overrides/components/-","value":{"name":"managedserviceaccount-preview","enabled":true}}]'
-----

[#adding-supporting-objects]
== Adding Supporting Objects

Lastly, we will add some supporting OpenShift resources for automation. We will add a namespace `ztp-day2-automation` which our automation Policy and PolicyAutomation will belong to, along with a Secret configuring ACM's authorization to access the AAP Controller through the controller's auth token.

[.console-input]
[source,bash]
-----
cat << EOF | oc apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-day2-automation
EOF

cat << EOF | oc -n ztp-day2-automation apply -f -
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aap-controller-token
  namespace: ztp-day2-automation
  labels:
    cluster.open-cluster-management.io/type: ans
    cluster.open-cluster-management.io/credentials: ""
stringData:
  host: ${ANSIBLE_CTRL_URL}
  token: $(cat ~/5g-deployment-lab/tower_token) 
EOF
-----
