= Crafting the Cluster CNF Operators Configs
include::_attributes.adoc[]
:profile: 5g-ran-lab

In the previous section we created the infrastructure as code (IaC) for our `SNO2` cluster using the `SiteConfig` object. In this section we are going to create the configuration as code (CaC) for our clusters by using the `PolicyGenTemplate` object.

We described how `PolicyGenTemplate` works in detail xref:policygen-deepdive.adoc#policies-templating[here], so let's jump directly to the creation of the different templates.

[#crafting-common-policies]
== Crafting Common Policies

The common policies apply to every cluster in our infrastructure that matches our binding rule. This policies are often used to configure things like CatalogSources, Operator Deployments, etc. that are common to all our clusters.

These configs may vary from release to release, that's why we create a `common-411.yaml` file. We will likely have a common configuration profile for each release we deploy.

IMPORTANT: If you check the binding rules you can see that we are targeting clusters labeled with `common: "ocp411"`. This label was set in the `InstallConfig` in the previous section.

1. Create the `common` PolicyGenTemplate for 4.11 SNOs:
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
[user@workstation ~]$ cat <<EOF > ~/5g-deployment-lab/ztp-repository/site-policies/common-policies/common-411.yaml
---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-policies"
spec:
  bindingRules:
    common: "ocp411"
  mcp: master
  remediationAction: inform
  sourceFiles:
    - fileName: OperatorHub.yaml
      policyName: operator-catalog-411
    - fileName: DefaultCatsrc.yaml
      metadata:
        name: redhat-operator-index
      spec:
        image: infra.5g-deployment.lab:8443/redhat/redhat-operator-index:v4.11
      policyName: operator-catalog-411            
EOF
-----

[#crafting-group-policies]
== Crafting Group Policies

The group policies apply to a group of clusters that typicall have something in common, for example they are SNOs or they have SR-IOV cards, etc.

The CNF team has prepared some common tuning configurations that should be applied on every SNO DU deployed. In this section we will be crafting these configurations.

IMPORTANT: If you check the binding rules you can see that we are targeting clusters labeled with `group-du-sno: ""`. This label was set in the `InstallConfig` in the previous section.

1. Create the `group` PolicyGenTemplate for SNOs:
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
[user@workstation ~]$ cat <<EOF > ~/5g-deployment-lab/ztp-repository/site-policies/group-policies/group-du-sno.yaml
---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "group-du-sno"
  namespace: "ztp-policies"
spec:
  bindingRules:
    group-du-sno: ""
  mcp: master
  remediationAction: inform
  sourceFiles:
    - fileName: ReduceMonitoringFootprint.yaml
      policyName: du-profile-wave1
    - fileName: ConsoleOperatorDisable.yaml
      policyName: du-profile-wave10
    - fileName: DisableSnoNetworkDiag.yaml
      policyName: du-profile-wave10   
EOF
-----

[#crafting-zone-policies]
== Crafting Zone Policies

Zone policies apply to a group of clusters that share a specific zone. Zone can mean multiple things to different people, it can be a region, a city, a physical location, etc.

We are going to create some policies that apply to our clusters located in `Europe`. For example, all our clusters in `Europe` use the Local Storage Operator to configure their storage, let's craft that policy:

1. Create the `zone` PolicyGenTemplate for clusters in Europe:
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
[user@workstation ~]$ cat <<EOF > ~/5g-deployment-lab/ztp-repository/site-policies/zone-policies/zone-europe.yaml
---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "zone-europe"
  namespace: "ztp-policies"
spec:
  bindingRules:
    du-zone: "europe"
  mcp: master
  remediationAction: inform
  sourceFiles:
    - fileName: StorageNS.yaml
      policyName: storage-operator
    - fileName: StorageOperGroup.yaml
      policyName: storage-operator
    - fileName: StorageSubscription.yaml
      spec:
        source: redhat-operator-index
      policyName: storage-operator
    - fileName: StorageOperatorStatus.yaml
      policyName: storage-operator 
EOF
-----

[#crafting-site-policies]
== Crafting Site Policies

Site policies apply to a specific cluster/s in our site, they usually configure stuff that is very specific to a single cluster or to a small subset of clusters. For example we could configure storage for a group of clusters if those share the same hardware, disks configurations, etc. otherwise we will need to have different bindings for different clusters.

We are going to create the `PerformanceProfile` and storage configurations for our SNO2 cluster.

1. Create the `sno2` PolicyGenTemplate for the `SNO2` cluster in our `5glab` site:
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
[user@workstation ~]$ cat <<EOF > ~/5g-deployment-lab/ztp-repository/site-policies/site-policies/site-sno2.yaml
---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "site-sno2"
  namespace: "ztp-policies"
spec:
  bindingRules:
    du-site: "sno2"
  mcp: master
  remediationAction: inform
  sourceFiles:
    - fileName: StorageLV.yaml
      spec:
        storageClassDevices:
          - storageClassName: "lso-fs"
            volumeMode: Filesystem
            fsType: xfs
            devicePaths:
              - /dev/vdb
      policyName: storage-configuration
    - fileName: StorageClass.yaml
      metadata:
        name: lso-fs
      policyName: storage-configuration
    - fileName: PerformanceProfile.yaml
      policyName: "performance-policy"
      metadata:
        annotations:
          kubeletconfig.experimental: |
            {"topologyManagerScope": "pod",
             "systemReserved": {"memory": "8Gi"}
            }
      spec:
        additionalKernelArgs:
        - "firmware_class.path=/var/lib/firmware/"
        - "nohz_full=8-11"          
        - "crashkernel=1024M"
        - "efi=runtime"
        cpu:
          isolated: "8-11"
          reserved: "0-7"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
          - count: 8
            size: 1G
        numa:
          topologyPolicy: single-numa-node
        realTimeKernel:
          enabled: false
        globallyDisableIrqLoadBalancing: false
    - fileName: TunedPerformancePatch.yaml
      policyName: "tuned-policy"
      spec:
        profile:
          - name: performance-patch
            data: |
              [main]
              summary=Configuration changes profile inherited from performance created tuned
              include=openshift-node-performance-openshift-node-performance-profile
              [bootloader]
              cmdline_crash=nohz_full=8-11
              [sysctl]
              kernel.timer_migration=1
              [scheduler]
              group.ice-ptp=0:f:10:*:ice-ptp.*
              [service]
              service.stalld=start,enable
              service.chronyd=stop,disable
EOF
-----

[#configure-kustomization-for-policies]
== Configure Kustomization for Policies

We need to create the required kustomization as we did for SiteConfigs, in this case policies also require a namespace where these will be created so we will create the required namespace and the kustomization.

1. Policies need to live in a namespace, let's add it to the repo:
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
[user@workstation ~]$ cat <<EOF > ~/5g-deployment-lab/ztp-repository/site-policies/policies-namespace.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-policies
  labels:
    name: ztp-policies
EOF
-----
+
3. Create the required Kustomization files
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
[user@workstation ~]$ cat <<EOF > ~/5g-deployment-lab/ztp-repository/site-policies/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - common-policies/common-411.yaml
  - group-policies/group-du-sno.yaml
  - zone-policies/zone-europe.yaml
  - site-policies/site-sno2.yaml
resources:
  - policies-namespace.yaml
EOF
-----
+
4. At this point we can push the changes to the repo and continue to the next section.
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
[user@workstation ~]$ cd ~/5g-deployment-lab/ztp-repository
[user@workstation ztp-repository]$ git add --all
[user@workstation ztp-repository]$ git commit -m 'Added policies information'
[user@workstation ztp-repository]$ git push origin main
[user@workstation ztp-repository]$ cd ~
-----