= Deployment Considerations
include::_attributes.adoc[]
:profile: 5g-ran-lab

A RAN deployment requires of multiple pieces of the stack being properly configured. In this section, we will present the most common ones.

[#hardware-configurations]
== Hardware configurations

RAN deployments usually run on top of baremetal servers, and as such, is of vital importance to have a proper configuration at the hardware level to meet the required expectations of the RAN workloads.

[#bios-settings]
=== BIOS Settings

NOTE: Depending on your hardware vendor the naming of the following features may vary.

* CPU Power and Performance Policy must be set to `Performance`.
* Energy efficiency settings must be set to `Disabled`.
* SR-IOV and VT-D must be set to `Enabled`.
* Boot Mode must be set to `UEFI`.
* Storage should be configured with a `RAID1` at least.

[#networking]
== Networking

IPv4 and IPv6 are both supported for RAN deployments, when using IPv6 only disconnected mode will be supported. 

You can have different networks for your different DUs, but keep in mind that these networks need to have connectivity to the network where the RHACM Hub is running.

When using IPv6, SLAAC addressing is discouraged.

[#disconnected-environments]
== Disconnected Environments

We define as _disconnected_ environment, an environment where there is no direct connectivity to the Internet.

There are two kinds of disconnected environments that we have identified.

[#connected-proxy]
=== Connected through proxy

Connected through proxy environments do not require extra infrastructure components to complete the installation since the proxy will provide access to the Internet and the installer will be able to grab all the required bits. If we want to speed up the installation or consume artifacts local to the environment we are installing we can deploy the infrastructure components described in the section below.

[#fully-disconnected]
=== Fully disconnected

When there is no connection to the Internet we need to mirror the required artifacts to run an OpenShift installation in our infrastructure. The required infrastructure components will be:

* HTTP Server to store RHCOS artifacts (images, rootfs, etc.)
* Container Registry to store OCP and OLM images

In a future section we will cover the deployment and mirroring of the required bits.

[#git-repo-structure]
== Git Repository Structure

When preparing a Git repository for running ZTP deployments we identified two potential ways of structuring the repository for GitOps: using branches or using folders. At this point, we can say that while branches have been used for structuring the different environments in the past, today, the preferred approach is using folders.

In our Git repository we will have the following folder structure:

[.console-input]
[source,bash,subs="attributes+,+macros"]  
----
.
├── site-configs
│   └── pre-reqs
│       └── ztp-sno
└── site-policies
    ├── common-policies
    ├── group-policies
    ├── site-policies
    └── zone-policies
----

* `site-configs`: This folder is used to store the different SiteConfigs describing the environments we will deploy through ZTP.
** `pre-reqs`: This folder is used to store the different configurations that are required for the deployment of the environments, things like: pull secrets, bmc credentials, etc.

* `site-policies`: This folder has different sub-folders storing different sets of PolicyGenTemplates.
** `common-policies`: This folder is used to store PolicyGenTemplates that apply to all clusters.
** `group-policies`: This folder is used to store PolicyGenTemplates that apply to a group of clusters.
** `site-policies`: This folder is used to store PolicyGenTemplates that apply to specific clusters.
** `zone-policies`: This folder is used to store PolicyGenTemplates that apply to clusters in a specific zone.
