= Introduction
include::_attributes.adoc[]
:profile: 5g-ran-lab

Welcome to this lab focused on deploying 5G RAN on OpenShift, designed to enhance your understanding and practical skills.

The first part of this lab introduces the essential concepts for planning and executing a 5G RAN Deployment on OpenShift. The second part involves a practical scenario where you will deploy RAN-enabled OCP using ZTP technologies and methodologies.

Since the second part requires a lab environment, we recommend ordering it before starting the first part to ensure it is ready when needed. If you are a Red Hat employee, you can order a pre-configured lab environment through the https://demo.redhat.com[Red Hat Demo Platform]. Please note that running this lab incurs a cost of approximately $56. When the lab is launched, by default you will have 12 hours to complete it before it is destroyed. The estimated total duration for completing the lab is approximately 12 hours, including 2 hours for provisioning, 5 hours for hands-on work, and a 5-hour buffer. If additional time is required, the duration can be manually extended up to a maximum of 24 hours.

For users without access to the demo platform, an alternative guide for deploying the lab environment is available at xref:lab-environment.adoc[here].

[#lab-aim]
== Who is this lab aimed at?

The lab is aimed at technical profiles working with OpenShift who are interested in any of these areas:

* Professionals interested in managing cluster fleets using GitOps methodologies.
* Working with telecom customers/partners in projects involving RAN workloads.

[#lab-software-versions]
== Lab Software Versions

The lab is based on the following software versions:

* HUB Cluster OpenShift {hub-cluster-ocp-version}.
* SNO Cluster OpenShift {sno-cluster-version1} and {sno-cluster-version2}.
* RHACM {rhacm-version}.
* MCE {mce-version}.
* PolicyGenTool {policygentool-version}.