= Introduction
include::_attributes.adoc[]
:profile: 5g-ran-lab

Welcome to this lab focused on deploying 5G RAN on OpenShift, designed to enhance your understanding and practical skills.

The first part of this lab introduces the essential concepts for planning and executing a 5G RAN Deployment on OpenShift. The second part involves a practical scenario where you will deploy RAN-enabled OCP using ZTP technologies and methodologies.

[#lab-aim]
== Who is this lab aimed at?

The lab is aimed at technical profiles working with OpenShift who are interested in any of these areas:

* Professionals interested in managing cluster fleets using GitOps methodologies.
* Working with telecom customers/partners in projects involving RAN workloads.

[#lab-software-versions]
== Lab Software Versions

The lab is based on the following software versions:

* HUB Cluster OpenShift {hub-cluster-ocp-version}.
* SNO Cluster OpenShift {sno-cluster-version1} and {sno-cluster-version2}.
* RHACM {rhacm-version}.
* MCE {mce-version}.
* PolicyGenTool {policygentool-version}.