= Lab Environment
include::_attributes.adoc[]
:profile: 5g-ran-lab

This section describes how to deploy your own lab environment.

CAUTION: If you are a Red Hatter, you can order a lab environment on the https://demo.redhat.com[Red Hat Demo Platform]. You just need to order the lab named `5G RAN Deployment on OpenShift`.

[#lab-requirements]
== Lab Requirements

RHEL 8.X box with access to the Internet. This lab relies on KVM, so you need to have the proper virtualization packages already installed. It is highly recommended to use a bare-metal host. Our lab environment has the following specs:

* 64 cores in total, with or without hyperthreading enabled.
* 200GiB Memory.
* 1 TiB storage.

IMPORTANT: These instructions have been tested in a RHEL 8.8, we cannot guarantee that other operating systems (even RHEL-based) will work. We won't be providing support out of RHEL 8.

These are the steps to install the required packages on a RHEL 8.8 server:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
yum -y install libvirt libvirt-daemon-driver-qemu qemu-kvm
usermod -aG qemu,libvirt $(id -un)
newgrp libvirt
systemctl enable --now libvirtd
-----

[#lab-deployment]
== Lab Deployment

IMPORTANT: All the steps in the below sections must be run as `root` user on the hypervisor host.

[#install-kcli]
=== Install kcli

We use https://github.com/karmab/kcli[kcli] to do several things, like managing VMs, deploying the first OCP cluster, etc. Additional kcli documentation can be found at `https://kcli.readthedocs.io`

IMPORTANT: Below commands must be executed from the hypervisor host as root if not specified otherwise.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf -y copr enable karmab/kcli
dnf -y install kcli bash-completion vim jq tar git ipcalc python3-pyOpenSSL
-----

[#install-oc-kubectl]
=== Install oc/kubectl CLIs

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli download oc -P version=stable -P tag='{kcli-tools-tag}'
kcli download kubectl -P version=stable -P tag='{kcli-tools-tag}'
mv kubectl oc /usr/bin/
-----

[#configure-disconnected-network]
=== Configure Disconnected Network

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli create network -c 192.168.125.0/24 -P dns=false -P dhcp=false --domain 5g-deployment.lab 5gdeploymentlab
-----

[#configure-local-dns-dhcp-server]
=== Configure Local DNS/DHCP Server

NOTE: If you're using MacOS and you're getting errors while running `sed -i` commands, make sure you are using `gsed`: `brew install gnu-sed`.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf -y install dnsmasq policycoreutils-python-utils
mkdir -p /opt/dnsmasq/include.d/
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/dnsmasq/dnsmasq.conf -o /opt/dnsmasq/dnsmasq.conf
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/dnsmasq/upstream-resolv.conf -o /opt/dnsmasq/upstream-resolv.conf
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/dnsmasq/hub.ipv4 -o /opt/dnsmasq/include.d/hub.ipv4
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/dnsmasq/sno1.ipv4 -o /opt/dnsmasq/include.d/sno1.ipv4
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/dnsmasq/sno2.ipv4 -o /opt/dnsmasq/include.d/sno2.ipv4
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/dnsmasq/infrastructure-host.ipv4 -o /opt/dnsmasq/include.d/infrastructure-host.ipv4
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/dnsmasq/dnsmasq-virt.service -o /etc/systemd/system/dnsmasq-virt.service
touch /opt/dnsmasq/hosts.leases
semanage fcontext -a -t dnsmasq_lease_t /opt/dnsmasq/hosts.leases
restorecon /opt/dnsmasq/hosts.leases
sed -i "s/UPSTREAM_DNS/1.1.1.1/" /opt/dnsmasq/upstream-resolv.conf
systemctl daemon-reload
systemctl enable --now dnsmasq-virt
systemctl mask dnsmasq
-----

[#configure-local-dns-as-primary-server]
=== Configure Local DNS as Primary Server

The default upstream DNS is set to 1.1.1.1 in `/opt/dnsmasq/upstream-resolv.conf`. There might be cases in your local environment where the hypervisor may not reach it. So, notice that you must change it to a different DNS that allows you to resolve public hostnames. Once changed, remember to restart the dnsmasq-virt service.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
curl -L https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/hypervisor/forcedns -o /etc/NetworkManager/dispatcher.d/forcedns
chmod +x /etc/NetworkManager/dispatcher.d/forcedns
systemctl restart NetworkManager
/etc/NetworkManager/dispatcher.d/forcedns
-----

[#disable-firewall]
=== Disable Firewall

You can also create the required rules in the firewall if you want, but for the sake of simplicity we are disabling the firewall.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
systemctl disable firewalld iptables
systemctl stop firewalld iptables
iptables -F
systemctl restart libvirtd
-----

[#configure-webcache]
=== Configure Webcache

The webcache is basically an Apache httpd container serving the RHCOS live ISO and rootfs images locally. They are required for provisioning OCP clusters.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
curl -L https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/webcache/podman-webcache.service -o /etc/systemd/system/podman-webcache.service
mkdir -p /opt/webcache/data
curl -L {rhcos-rootfs-url} -o /opt/webcache/data/{rhcos-rootfs-filename}
curl -L {rhcos-liveiso-url} -o /opt/webcache/data/{rhcos-liveiso-filename}
systemctl daemon-reload
systemctl enable podman-webcache --now
-----

[#install-ksushytool]
=== Install Ksushy Tool

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
pip3 install cherrypy
kcli create sushy-service --ssl --port 9000
systemctl enable ksushy --now
-----

[#configure-disconnected-registry]
=== Configure Disconnected Registry

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf -y install podman httpd-tools
REGISTRY_NAME=infra.5g-deployment.lab
mkdir -p /opt/registry/{auth,certs,data,conf}
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/registry/registry-key.pem -o /opt/registry/certs/registry-key.pem
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/registry/registry-cert.pem -o /opt/registry/certs/registry-cert.pem
htpasswd -bBc /opt/registry/auth/htpasswd admin r3dh4t1! 
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/registry/config.yml -o /opt/registry/conf/config.yml
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/registry/podman-registry.service -o /etc/systemd/system/podman-registry.service
systemctl daemon-reload
systemctl enable podman-registry --now
cp /opt/registry/certs/registry-cert.pem /etc/pki/ca-trust/source/anchors/
update-ca-trust
podman login --authfile auth.json -u admin  infra.5g-deployment.lab:8443 -p r3dh4t1!
-----

NOTE: Link to additional configuration documentation of a disconnected registry: {disconnected-registry-docs}

[#configure-git-server]
=== Configure Git Server

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
mkdir -p /opt/gitea/
chown -R 1000:1000 /opt/gitea/
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/gitea/podman-gitea.service -o /etc/systemd/system/podman-gitea.service
systemctl daemon-reload
systemctl enable podman-gitea --now
podman exec --user 1000 gitea /bin/sh -c 'gitea admin user create --username student --password student --email student@5g-deployment.lab --must-change-password=false --admin'
curl -u 'student:student' -H 'Content-Type: application/json' -X POST --data '{"service":"2","clone_addr":"https://github.com/RHsyseng/5g-ran-deployments-on-ocp-lab.git","uid":1,"repo_name":"5g-ran-deployments-on-ocp-lab"}' http://infra.5g-deployment.lab:3000/api/v1/repos/migrate
curl -u 'student:student' -H 'Content-Type: application/json' -X POST --data '{"service":"2","clone_addr":"https://github.com/RHsyseng/5g-ran-lab-aap-integration-tools.git","uid":1,"repo_name":"aap-integration-tools"}' http://infra.5g-deployment.lab:3000/api/v1/repos/migrate
-----

WARNING: It could be possible that the last few commands do not work at the first time since the registry container image is being pulled and then started. If that's the case, try them once again after a couple of seconds.

[#configure-ntp-server]
=== Configure NTP Server

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf install chrony -y
cat <<EOF > /etc/chrony.conf
server time.cloudflare.com iburst
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
keyfile /etc/chrony.keys
leapsectz right/UTC
logdir /var/log/chrony
bindcmdaddress ::
allow 192.168.125.0/24
EOF
systemctl enable chronyd --now
-----

[#configure-access-to-cluster-apps]
=== Configure Access to Cluster Apps

In order to access the hub cluster we will deploy an HAProxy that will be listening on the public interface of the Hypervisor host.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf install haproxy -y
semanage port -a -t http_port_t -p tcp 6443
curl -L https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/haproxy/haproxy.cfg -o /etc/haproxy/haproxy.cfg
systemctl enable haproxy --now
-----

After that you need to add the following entries to your /etc/hosts file:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
<HYPERVISOR_REACHABLE_IP> infra.5g-deployment.lab api.hub.5g-deployment.lab multicloud-console.apps.hub.5g-deployment.lab console-openshift-console.apps.hub.5g-deployment.lab oauth-openshift.apps.hub.5g-deployment.lab openshift-gitops-server-openshift-gitops.apps.hub.5g-deployment.lab assisted-service-multicluster-engine.apps.hub.5g-deployment.lab api.sno1.5g-deployment.lab api.sno2.5g-deployment.lab
-----

[#create-openshift-nodes-vms]
=== Create SNO Nodes VMs

Before running the following commands, make sure you have generated a SSH key pair in your default location `~/.ssh/`. That SSH key will allow you to connect to the VMs you are about to create:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli create pool -p /var/lib/libvirt/images default
kcli create vm -P start=False -P uefi_legacy=true -P plan=hub -P memory=24000 -P numcpus=12 -P disks=[200,200] -P nets=['{"name": "5gdeploymentlab", "mac": "aa:aa:aa:aa:02:01"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0201 -P name=sno1
kcli create vm -P start=False -P uefi_legacy=true -P plan=hub -P memory=24000 -P numcpus=12 -P disks=[200,200] -P nets=['{"name": "5gdeploymentlab", "mac": "aa:aa:aa:aa:03:01"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0301 -P name=sno2
-----

If you need or want to connect to any of the VMs you can do so by just executing:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli ssh <VM_name>
-----


[#deploy-openshift-hub-cluster]
=== Deploy OpenShift Hub Cluster

IMPORTANT: This step requires a valid OpenShift Pull Secret placed in /root/openshift_pull.json. Notice that you can replace the admin or developer's password shown below for any other.

NOTE: If you're using MacOS and you're getting errors while running `sed -i` commands, make sure you are using `gnu-sed`: `brew install gnu-sed`.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
curl -sL https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/hub-cluster/hub.yml -o /root/hub.yml
sed -i "s/CHANGE_ADMIN_PWD/admin/" hub.yml
sed -i "s/CHANGE_DEV_PWD/developer/" hub.yml
cd /root/
kcli create cluster openshift --pf hub.yml
-----

This will take around 40 minutes to complete.

If the installation fails for whatever reason, you will need to delete all the VMs that were created and execute the same procedure again. So, first remove the plans, which actually will remove all VMs:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----

# kcli list plan
+------+--------------------------------------------------------+
| Plan |                          Vms                           |
+------+--------------------------------------------------------+
| hub  | hub-ctlplane-0,hub-ctlplane-1,hub-ctlplane-2,sno1,sno2 |
+------+--------------------------------------------------------+

# kcli delete plan hub -y
hub-ctlplane-0 deleted on local!
hub-ctlplane-1 deleted on local!
hub-ctlplane-2 deleted on local!
sno1 deleted on local!
sno2 deleted on local!
Plan hub deleted!
-----

And then create the VMs again as explained in the previous section link:lab-environment.html#create-openshift-nodes-vms[Deploy OpenShift Hub Cluster].


[#configure-openshift-hub-cluster]
=== Configure OpenShift Hub Cluster

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
export KUBECONFIG=~/.kcli/clusters/hub/auth/kubeconfig
oc -n openshift-storage wait lvmcluster lvmcluster --for=jsonpath='{.status.state}'=Ready --timeout=900s
oc patch storageclass lvms-vg1 -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
curl https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/hub-cluster/argocd-patch.json -o /tmp/argopatch.json
oc patch argocd openshift-gitops -n openshift-gitops --type=merge --patch-file /tmp/argopatch.json
oc wait --for=condition=Ready pod -lapp.kubernetes.io/name=openshift-gitops-repo-server -n openshift-gitops
oc -n openshift-gitops adm policy add-cluster-role-to-user cluster-admin -z openshift-gitops-argocd-application-controller
-----

[#deploy-openshift-hub-cluster-operators]
=== Deploy OpenShift HUB Cluster Operators

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
oc apply -f https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/hub-cluster/hub-operators-argoapps.yaml
-----

[#deploy-sno1-cluster-without-ztp]
=== Deploy SNO1 Cluster (without ZTP)

A SNO is deployed outside the ZTP workflow so students can import it and see how that workflow works.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
curl -L http://infra.5g-deployment.lab:3000/student/5g-ran-deployments-on-ocp-lab/raw/branch/{branch}/lab-materials/lab-env-data/hypervisor/ssh-key -o /root/.ssh/snokey
chmod 400 /root/.ssh/snokey
oc apply -f https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/hub-cluster/sno1-argoapp.yaml
-----

Once the cluster is deployed, the kubeconfig can be gathered as follows:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
oc -n sno1 get agentclusterinstall,agent
NAME                                                    CLUSTER   STATE
agentclusterinstall.extensions.hive.openshift.io/sno1   sno1      adding-hosts

NAME                                                                    CLUSTER   APPROVED   ROLE     STAGE
agent.agent-install.openshift.io/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0201   sno1      true       master   Done

oc extract secret/sno1-admin-kubeconfig --to=- -n sno1 > /root/sno1kubeconfig
oc --kubeconfig /root/sno1kubeconfig get nodes,clusterversion

NAME                      STATUS   ROLES                         AGE     VERSION
node/openshift-master-0   Ready    control-plane,master,worker   94m     {sno-cluster-version1-kubeversion}

NAME                                         VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
clusterversion.config.openshift.io/version   {sno-cluster-version1-cvo}    True        False         75m     Cluster version is {sno-cluster-version1-cvo}
-----

[#configure-aap]
=== Configure Ansible Automation Platform

IMPORTANT: This step requires a valid Ansible Automation Platform Manifest. You can {aap-get-manifest-docs}[read the official docs to get one].

Before proceeding, you need to wait for the AAP to be fully deployed in the Hub cluster.

This configuration requires of having ansible deployed in the hypervisor host along with some ansible collections.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf install ansible-core python3.11-pip -y
python3.11 -m pip install kubernetes
ansible-galaxy collection install awx.awx
ansible-galaxy collection install infra.controller_configuration
ansible-galaxy collection install kubernetes.core
-----

Next, let's create a playbook that will configure the automation controller for us:

NOTE: Change the `aap_manifest_file_path` var value to match the path where you stored the manifest in the hypervisor host and change the value for the `student` user.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
curl -L https://raw.githubusercontent.com/RHsyseng/5g-ran-deployments-on-ocp-lab/{branch}/lab-materials/lab-env-data/aap2/configure-aap.yaml -o /root/configure-aap.yaml
ansible-playbook /root/configure-aap.yaml -e strong_student_password=yourstrongstudentpassword -e aap_manifest_file_path=/path/to/your/manifest
-----

Once the playbook finishes we should have access to the AAP Controller at https://automation-aap.apps.hub.5g-deployment.lab with the student user and the password you configured.