= Introduction to the lab environment
include::_attributes.adoc[]
:profile: 5g-ran-lab

Before jumping into the hands-on sections let's get familiar with the lab environment we have deployed.

[#git-server]
== Git Server

A https://github.com/go-gitea/gitea[gitea] server is running on the infrastructure host, you can reach it out at http://infra.5g-deployment.lab:3000/.

Credentials for the git server:

* Username: `student` 
* Password: `student`

[#container-registry]
== Container Registry

A https://docs.openshift.com/container-platform/4.11/installing/disconnected_install/installing-mirroring-creating-registry.html[container registry] is running on the infrastructure host, you can reach it out at https://infra.5g-deployment.lab:8443/.

Credentials for the container registry:

* Username: `admin` 
* Password: `r3dh4t1!`

NOTE: If you receive an error message regarding the certificate please re-run update-ca-trust on the hypervisor or add `--tls-verify=false` to the command line. 

[#openshift-hub-cluster]
== OpenShift Hub Cluster

An OpenShift cluster is running on the infrastructure host, you can reach it out at https://console-openshift-console.apps.hub.5g-deployment.lab and https://api.hub.5g-deployment.lab:6443

Credentials for the OCP cluster (htpassidp provider):

* Username: `admin` 
* Password: The password is randomly generated for each environment, and can be found in the following path: `/root/cred-admin.txt` in your hypervisor host or in the e-mail you received when the lab was ready.

