= Introduction to the lab environment
include::_attributes.adoc[]
:profile: 5g-ran-lab

Before jumping into the hands-on sections let's get familiar with the lab environment we have available.

CAUTION: The following lab sections rely on having a lab environment accessible in order to do the hands-on work. If you're a Red Hatter you can order a lab environment already setup for you on the https://demo.redhat.com[Red Hat Demo Platform]. You just need to order the lab named `5G RAN Deployment on OpenShift`. Notice that it has a cost of ~ $56 to run through the lab. When the lab is launched, by default you will have 12 hours to complete it before it is destroyed. The estimated time to finish the lab might look like 12 hours total (2h provisioning time, 5h lab work, 5h margin). If you need further time, it can be manually extended up to 24h in total. If you still need to deploy a lab environment, follow the guide available xref:lab-environment.adoc[here].

[#git-server]
== Git Server

A https://github.com/go-gitea/gitea[gitea] server is running on the infrastructure host, you can reach it out at http://infra.5g-deployment.lab:3000/.

Credentials for the git server:

* Username: `student` 
* Password: `student`

[#container-registry]
== Container Registry

A https://docs.openshift.com/container-platform/4.13/installing/disconnected_install/installing-mirroring-creating-registry.html[container registry] is running on the infrastructure host, you can reach it out at https://infra.5g-deployment.lab:8443/.

Credentials for the container registry:

* Username: `admin` 
* Password: `r3dh4t1!`

NOTE: If you receive an error message regarding the certificate please re-run update-ca-trust on the hypervisor or add `--tls-verify=false` to the command line. 

[#openshift-hub-cluster]
== OpenShift Hub Cluster

An OpenShift cluster is running on the infrastructure host, you can reach it out at https://console-openshift-console.apps.hub.5g-deployment.lab and https://api.hub.5g-deployment.lab:6443

Credentials for the OCP cluster (htpassidp provider):

* Username: `admin` 
* Password: The password is randomly generated for each environment, and can be found in the following path: `/root/cred-admin.txt` in your hypervisor host or in the e-mail you received when the lab was ready.

[#automation-hub-and-controller]
== AAP Automation Hub and Controller

The Automation Hub can be reached at https://automation-hub-aap.apps.hub.5g-deployment.lab

Credentials for Automation Hub:

* Username: `admin`
* Password: Retrieve the password by logging into oc and running:

[.console-input]
[source,bash]
-----
oc -n aap get secret automation-hub-admin-password -o jsonpath='{.data.password}' | base64 -d
-----

The Automation Controller can be reached at https://automation-aap.apps.hub.5g-deployment.lab
 
Credentials for Automation Controller:
 
* Username: `admin`
* Password: Retrieve the password by logging into oc and running: 

[.console-input]
[source,bash]
-----
oc -n aap get secret automation-admin-password -o jsonpath='{.data.password}' | base64 -d
-----
