= Introduction to Telco Related Infrastructure Operators
include::_attributes.adoc[]
:profile: 5g-ran-lab

When working on RAN environments there are a set of operators that will be common to almost all of them. In this section we will introduce what those operators are and what they are used for.

[#node-tuning-operator]
== Node Tuning Operator

The Node Tuning Operator helps you manage node-level tuning by orchestrating the TuneD daemon and other OS level tuning. In the context of RAN deployments it is used to achieve low latency performance by using the Performance Profile controller.

In RAN environments we will leverage the PerformanceProfile API in order to:

* Update the kernel to kernel-rt.
* Configure CPUs for housekeeping (reserved CPUs).
* Configure CPUs for running workloads (isolated CPUs).
* Configure workloadHints to enable tuning of power savings vs performance. {workload-hints-doc}[More here].

The Node Tuning Operator is part of the standard OpenShift installation.

You can read more about the NTO {nto-docs}[here].

[#sriov-operator]
== SR-IOV Operator

This Operator helps you manage SR-IOV network devices and network attachments. You can think of an SR-IOV NIC like a hypervisor for NICs, you have a physical NIC and you can create (a limited number of) virtualized NICs out of it.

We usually refer to this virtualized NICs as virtual functions (VFs), and these are exposed in the containers in order to provide extra networks to workloads. These VFs are "slices" of the underlying NIC which are passed into the container as hardware devices. This allows the container direct access to that "slice" of the NIC and is typically used to provide high performance access to networking.

You can read more about the SR-IOV operator {sriov-docs}[here].

[#ptp-operator]
== PTP Operator

Precision Time Protocol (PTP) is used to synchronize clocks in a network, as discussed xref:5g-ran-context.adoc#ptp[previously]. When used in conjunction with hardware support, PTP is capable of sub-microsecond accuracy, and is more accurate than Network Time Protocol (NTP).

The PTP Operator can be used to configure PTP on OpenShift nodes.

Some extra PTP information you may find useful:

* {ptp-docs}[PTP Operator Official Docs].
* PTP blog posts on cloud.redhat.com https://cloud.redhat.com/blog/delivering-high-precision-clock-synchronization-for-low-latency-5g-networks-with-openshift-part-1[part 1] and https://cloud.redhat.com/blog/delivering-high-accuracy-clock-synchronization-for-5g-networks-with-openshift-part-2[part 2].

[#accelerators-operators]
== Accelerators Operators

Specialized hardware devices can be used to accelerate 4G/LTE and 5G virtualized radio access networks (vRAN) workloads. The use of these devices increases the overall compute capacity of a commercial, off-the-shelf platform by offloading compute intensive tasks to dedicated hardware.

In order to manage these devices, there are multiple accelerator operators that we may need to deploy in our OpenShift clusters.
