apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  labels:
    openshift.io/cluster-monitoring: "true"
    workload.openshift.io/allowed: management
  annotations:
    workload.openshift.io/allowed: management
    ran.openshift.io/ztp-deploy-wave: "2"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: lvms-operator-operatorgroup
  namespace: openshift-storage
  annotations:
    operatorframework.io/bundle-unpack-min-retry-interval: 10m
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  targetNamespaces:
  - openshift-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: lvms-operator
  namespace: openshift-storage
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  channel: "stable-4.21"
  name: lvms-operator
  source: redhat-operator-index
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
