---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    installer.open-cluster-management.io/mce-subscription-spec: '{"source": "redhat-operator-index"}'
  name: multiclusterhub
  namespace: open-cluster-management
spec: 
  availabilityConfig: "Basic"
