---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    workload.openshift.io/allowed: management
  labels:
    openshift.io/cluster-monitoring: "true"
  name: aap
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: ansible-automation-platform-operator-operatorgroup
  namespace: aap
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: ansible-automation-platform-operator
  namespace: aap
spec:
  channel: stable-2.4-cluster-scoped
  name: ansible-automation-platform-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
