---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: aap
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: aap-gp
  namespace: aap
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aap-sub
  namespace: aap
spec:
  channel: stable-2.4-cluster-scoped
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operator-index
  sourceNamespace: openshift-marketplace
